{% if not WITH_SOLVERS is defined %}
  {% set WITH_SOLVERS = 1 %}
{% endif %}
{% set WITH_SOLVERS = WITH_SOLVERS|int %}

package:
  {% if WITH_SOLVERS %}
    name: ilastik-everything
  {% else %}
    name: ilastik-everything-no-solvers
  {% endif %}

    version: "" # build.sh will generate a __conda_version__.txt file

build:
  number: 6

requirements:
  build:
    - ilastik-deps-pc
    - ilastik-deps-pc-iiboost
    - ilastik-deps-carving >=1.1.6a7

  {% if WITH_SOLVERS %}
    - ilastik-deps-multicut
    - ilastik-deps-tracking
  {% else %}
    - ilastik-deps-multicut-no-solvers
    - ilastik-deps-tracking-no-solvers
  {% endif %}

    - ilastik-meta    # Needed to print ilastik.__version__

  run:
    - ilastik-deps-pc
    - ilastik-deps-pc-iiboost
    - ilastik-deps-carving >=1.1.6a7

  {% if WITH_SOLVERS %}
    - ilastik-deps-multicut
    - ilastik-deps-tracking
    - ilastik-versions 1.2 np111py27_14
  {% else %}
    - ilastik-deps-multicut-no-solvers
    - ilastik-deps-tracking-no-solvers
    - ilastik-versions-no-solvers 1.2 np111py27_14
  {% endif %}

    - ilastik-meta
    - ilastik-launch

test:
  requires:
    - nose
    
  imports:
    - lazyflow
    - volumina
    - ilastik

about:
  summary: "A meta-package for building all ilastik dependencies and downloading the ilastik-meta repo."

