{% set name = "fiji-ilastik" %}
{% set version = "1.8.2" %}
 
package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://maven.scijava.org/service/local/repositories/releases/content/org/ilastik/ilastik4ij/{{ version }}/ilastik4ij-{{ version }}.jar
  sha256: 7ed05f4941d6d870e70bae3ff7e183a1d750ea5ed63f0efaf6bcbac500c715a0

build:
  number: 0
  noarch: generic

requirements:
  host:
    - fiji >=20170530
  run:
    - fiji >=20170530
    - ilastik >=1.4.0b29
