package:
  name: bzip2
  version: 1.0.6

source:
  fn:  bzip2-1.0.6.tar.gz
  url: http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
  md5: 00b516f4704d4a7cb50a1d97e6e8e15b

about:
  home: http://www.bzip.org/
  license: BSD
  summary:  freely available, patent free, high-quality data compressor

