package:
  name: vigra

  # Transform tag:
  # Version-1-11-0 --> 1.11.0
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("Version-","")|replace("-", ".") %}

  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}

  version: {{tagged_version}}

source:
  git_url: https://github.com/ukoethe/vigra
  git_tag: HEAD

build:
  number: 1000
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}

  script_env:
    - VIGRA_SKIP_TESTS

requirements:
  build:
    - cmake
    - {{ compiler("cxx") }}
  host:
    - boost    {{ boost }}
    - fftw     3.3*
    - h5py     {{ h5py }}
    - hdf5     {{ hdf5 }}
    - jpeg     {{ jpeg }}
    - lemon    {{ lemon }}
    - libpng   {{ libpng }}
    - libtiff  {{ libtiff }}
    - nose
    - numpy    {{ numpy }}
    - python   {{ python }}
    - zlib     1.2*

  run:
    - boost {{ boost }}
    - fftw     3.3*
    - h5py
    - hdf5
    - jpeg
    - lemon
    - libpng
    - libtiff
    - nose
    - {{ pin_compatible("numpy")}}
    - python
    - zlib     1.2*

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

