{% if not WITH_CPLEX is defined %}
  {% set WITH_CPLEX = false %}
{% endif %}

{% if WITH_CPLEX == "0" %}
  {% set WITH_CPLEX = false %}
{% endif %}

{% if not WITH_EXTERNAL_LIBS is defined %}
  {% set WITH_EXTERNAL_LIBS = false %}
{% endif %}

{% if WITH_EXTERNAL_LIBS == "0" %}
  {% set WITH_EXTERNAL_LIBS = false %}
{% endif %}

package:
  {% if WITH_CPLEX %}
    name: opengm-with-cplex
  {% else %}
    name: opengm
  {% endif %}

    version: "2.3.7.post29"

source:
  git_url: https://github.com/ilastik/opengm
  #git_rev: d94f09af6d58eb6a14cd864c286fff34069637df # branch 'ilastik-build'
  git_rev: fc5abc1f3ec93225044c634151c080611928d0f3 # branch 'ilastik-build'

  patches:
    - patches/patchConicBundle.patch # Yes, we're patching the patch script (ignore ssl certificate problems)
    - patches/patchDAOOPT.sh.patch # Apparently old versions of wget don't choose the same default filename for github zip files.
    - patches/patchPlanarity.sh.patch # Apparently the mirror at http://jgaa.info is not reliable, but the parent website is.

build:
  number: 7

  #
  # You must build this recipe using 'conda build --numpy=X.Y'
  #
  {% if WITH_EXTERNAL_LIBS %}
    string: np{{np}}py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}_with_extlibs
  {% else %}
    string: np{{np}}py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}_no_extlibs
  {% endif %}

    detect_binary_files_with_prefix: true
    script_env:
      - WITH_CPLEX
      - WITH_EXTERNAL_LIBS
      - CPLEX_ROOT_DIR

requirements:
  build:
    - gcc 4.8.5 79992 # [linux]
    - boost 1.63.0
    - python >=2.7
    - numpy >=1.9,{{NPY_VER}}*
    - hdf5 1.8.17 # HDF5 is required for the python wrapper
    - vigra-headers-only 1.11.0.post36   # This version is known to work
    
    {% if WITH_CPLEX %}
    - cplex-shared # Need to make sure that cplex dylibs exist
    {% endif %}

  run:
    - libgcc 4.8.5 19993 # [linux]
    - boost 1.63.0
    - python {{PY_VER}}*
    - numpy  {{NPY_VER}}*
    - hdf5 1.8.17 # HDF5 is required for the python wrapper

    {% if WITH_CPLEX %}
    - cplex-shared # Need to make sure that cplex dylibs exist and are linked into the environment
    {% endif %}
    
    # At build time, vigra is needed on the C++ side for header-only stuff,
    # but isn't needed at runtime (e.g. for python stuff) 
    # - vigra >=1.11

test:
  {% if WITH_CPLEX %}
    imports:
      - opengm_with_cplex
  {% else %}
    imports:
      - opengm
  {% endif %}

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
  {% if WITH_CPLEX %}
    summary: 'A C++ Library for Discrete Graphical Models. This package was linked against the CPLEX commercial ILP solver, which you will need to install separately.'
  {% else %}
    summary: 'A C++ Library for Discrete Graphical Models'
  {% endif %}

    home: https://github.com/opengm/opengm
    license: GNU General Public License (GPL)
