package:
  name: lz4
  version: "128"

source:
  git_url: git://github.com/Cyan4973/lz4
  git_tag: "r128"

build:
  number: 1
  detect_binary_files_with_prefix: true

about:
  home: http://cyan4973.github.io/lz4
  license: Unknown
  summary: Extremely Fast Compression algorithm
