package:
    name: opengm-structured-learning-headers
    version: "2.3.4"

source:
    git_url: https://github.com/opengm/opengm.git
    git_tag: learning-experimental
    patches:
      - 0001-fix-elseif.diff

build:
  number: 3000
  string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make  # [not win]
  host:
    - libboost-devel {{ boost }}*
    - python
    - numpy >=1.16
    - hdf5 {{ hdf5 }}*

about:
    home: https://github.com/opengm/opengm
    license: GNU General Public License (GPL)
    summary: 'A C++ Library for Discrete Graphical Models (This package contains only headers.)'
