{% set name = "modulegraph" %}
{% set version = "0.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2824588c489c0ba6f815c066950400755e8e287da64bcddae4c0d6e76f8f5f3

build:
  number: 0
  entry_points:
    - modulegraph = modulegraph.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - altgraph >=0.15
    - pip
    - python
    - setuptools
  run:
    - altgraph >=0.15
    - python
    - setuptools

test:
  imports:
    - modulegraph
  commands:
    - modulegraph --help

about:
  home: http://bitbucket.org/ronaldoussoren/modulegraph
  license: MIT
  license_family: MIT
  summary: Python module dependency analysis tool
