package:
  name:
    z5py
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}
  version:
   {{tagged_version}}


source:
  git_url: https://github.com/constantinpape/z5
  git_tag: HEAD


build:
  number: 0
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - python {{ python }}
    - cmake
    - boost-cpp  {{ boost }}  # the boost version needs to be fixed, because we are linking against specific shared objects
    - xtensor {{ xtensor }}
    - xtensor-python {{ xtensor_python }}
    - numpy {{ numpy }}
    - nlohmann_json
    - blosc
    - bzip2
    - xz
    - zlib
  run:
    - python
    - boost-cpp
    - numpy
    - six
    - blosc
    - bzip2
    - xz
    - zlib


test:
  imports:
    - z5py
