mkdir build
cd build
cmake ..\
	-DCMAKE_INSTALL_PREFIX=${PREFIX} \
	-DCMAKE_PREFIX_PATH=${PREFIX} \
	-DWITH_BOOST=ON \
    -DWITH_HDF5=ON \
    -DBUILD_PYTHON_WRAPPER=OFF \
    -DBUILD_TESTING=OFF \
    -DBUILD_TUTORIALS=OFF \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_COMMANDLINE=OFF \

make -j${CPU_COUNT}
make install
