package:
  name: feast
  version: "1.1.3"

source:
  git_url: https://github.com/Craigacp/FEAST
  git_tag: "v1.1.3"

build:
  number: 0

requirements:
  build:
    - mitoolbox
  
  run:
    - mitoolbox

about:
  home: http://www.cs.man.ac.uk/~gbrown/fstoolbox/
  license: BSD
  summary: 'A FEAture Selection Toolbox for C/C++ & Matlab/Octave.'
