{% if not WITH_SOLVERS is defined %}
  {% set WITH_SOLVERS = 1 %}
{% endif %}
{% set WITH_SOLVERS = WITH_SOLVERS|int %}

package:
    {% set package_name = "ilastik-dependencies" %}

    {% if not WITH_SOLVERS %}
      {% set package_name = package_name + "-no-solvers" %}
    {% endif %}

    name: {{ package_name }}
    version: 1.4.5

build:
  number: 2


  track_features:
    # on osx we need to make sure that we install the numpy versions with openblas instead of mkl to prevent clashes with cplex
    - blas_openblas  # [osx]
#
# In general, we don't specify exact version requirements in each sub-package.
# But this file tracks the versions of all packages used in the release.
requirements:
  run:
    # -----------------------------------------------------------------
    # General dependencies
    # -----------------------------------------------------------------
    - python
    - numpy                     {{ numpy }}

    - appdirs
    - attrs
    - cachetools
    - decorator
    - fftw
    - future
    - greenlet
    - h5py                      {{ h5py }}
    - hdf5                      {{ hdf5 }}
    - jsonschema
    - matplotlib
    - networkx                  >={{ networkx }}
    - pandas                    {{ pandas }}*
    - pillow                    {{ pillow }}
    - psutil
    - pyopengl
    - pyqt
    - pyqtgraph
    - pytest                    {{ pytest }}*
    - pytest-qt
    - python-dateutil
    - pytz
    - qimage2ndarray
    - qt                        {{ qt }}*
    - readline                                 # [not win]
    - requests
    - scikit-image
    - scikit-learn              {{ sklearn }}*
    - setuptools
    - vigra                     {{ vigra }}
    - xarray
    - yapsy
    - z5py                      >={{ z5py }}

    # -----------------------------------------------------------------
    # packages built by us
    # -----------------------------------------------------------------
    - elf
    - fastfilters
    - lemon
    - pytiff
    - tifffile
    # -----------------------------------------------------------------
    # ilastik main packages developed by us
    # -----------------------------------------------------------------
    - ilastik-feature-selection
    - ilastikrag
    - ilastiktools
    - marching_cubes
    - ndstructs
    - numpy-allocation-tracking
    # configure additional neural network dependencies by adding them to the env
    # tiktorch pins bioimageio.* versions
    - tiktorch {{ tiktorch }}
    - vigra                     {{ vigra }}
    - wsdt

    # -----------------------------------------------------------------
    # Trackinghdf5
    # -----------------------------------------------------------------
    - dpct
    - hytra
    - mamutexport

{% if WITH_SOLVERS %}
    - multi-hypotheses-tracking-with-gurobi
    - multi-hypotheses-tracking-with-cplex
{% endif %}


    # -----------------------------------------------------------------
    # Multicut
    # -----------------------------------------------------------------
    - nifty


test:
  # Just give SOME test to ensure that the package can be installed at all.
  # (If there are no tests, the test environment isn't even created.)
  imports:
    - vigra

about:
  home: https://github.com/ilastik-conda-recipes
  license: BSD (3-clause)
  summary: 'Package for all dependencies needed to run ilastik'
