package:
    name: dpct
    version: "1.0"

source:
    git_url: https://github.com/chaubold/dpct
    git_tag: HEAD 

build:
  {% set build_num = 4 %}
  number: {{ build_num }}
  detect_binary_files_with_prefix: true

  string: py{{CONDA_PY}}_{{build_num}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - libgcc
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - patchelf # [linux]
    - boost 1.55.0
    - lemon
    - python {{PY_VER}}*

  run:
    - libgcc
    - patchelf # [linux]
    - boost 1.55.0
    - lemon
    - python {{PY_VER}}*

test:
  imports:
    - dpct

about:
    home: https://github.com/chaubold/dpct
    license: GNU General Public License (GPL)
    summary: 'Dynamic Programming Cell Tracking Solver Library'
