@echo off

REM This file is generated by bld.bat -- DO NOT EDIT!
REM
REM Delete a git repository if it has no uncommited/unpushed changes

if not exist "%PREFIX%\Library\src\vigra" goto :eof

cd "%PREFIX%\Library\src\vigra"
FOR /F "delims=" %%i IN ('git rev-parse --show-toplevel') DO SET REPO_ROOT=%%i
if "%REPO_ROOT%"=="" (
    REM if it not a git repo, simply delete it
    SET REPO_ROOT=%PREFIX%\Library\src\vigra
    goto :delete_directory
)

echo Checking if git repository "%REPO_ROOT%" can be removed.
cd "%REPO_ROOT%"

REM store paths to main repos and its subrepos
echo %REPO_ROOT%> _tmp_git_repos.txt
git submodule --quiet foreach --recursive "git rev-parse --show-toplevel" >> _tmp_git_repos.txt
if errorlevel 1 goto :eof

REM check for uncommitted changes and unpushed commits
call :create_empty_file _tmp_git_status.txt
call :create_empty_file _tmp_git_pushed.txt
FOR /F "delims=" %%i IN ('type _tmp_git_repos.txt') DO (
    cd "%%i"
    git status -uno -s -z >> "%REPO_ROOT%\_tmp_git_status.txt"
    git log --branches --not --remotes >> "%REPO_ROOT%\_tmp_git_pushed.txt"
)
if errorlevel 1 goto :eof

REM abort if there are uncommitted changes (_tmp_git_status.txt is non-empty)
for /f %%i in ("_tmp_git_status.txt") do set UNCOMMITTED_CHANGES=%%~zi
del _tmp_git_status.txt
if not "%UNCOMMITTED_CHANGES%"=="0" (
    echo Repository "%REPO_ROOT%" has uncommitted changes:
    git status -uno
    git submodule foreach --recursive "git status -uno"
    echo
    echo Commit your changes and remove the repository manually.
    echo
    goto :eof
)

REM abort if there are unpushed changes (_tmp_git_pushed.txt is non-empty)
cd "%REPO_ROOT%"
for /f %%i in ("_tmp_git_pushed.txt") do set UNPUSHED_CHANGES=%%~zi
del _tmp_git_pushed.txt
if not "%UNPUSHED_CHANGES%"=="0" (
    echo Repository "%REPO_ROOT%" has unpushed changes:
    git log --branches --not --remotes
    git submodule foreach --recursive "git log --branches --not --remotes"
    echo
    echo Push your changes and remove the repository manually.
    echo
    goto :eof
)

:delete_directory
cd "%PREFIX%"

echo Removing "%REPO_ROOT%".
del /F /S /Q "%REPO_ROOT%"
rmdir /S /Q  "%REPO_ROOT%"

goto :eof

REM create an empty file
REM     call :create_empty_file  "filename"
:create_empty_file
    copy /Y NUL "%~1" > NUL
    goto :eof
