package:
  name: ilastik-package
  version: "1.0.4"

build:
  number: 0
requirements:
  build:
    - git
  run:
    - ilastik-dependencies-no-solvers
    - ilastik-meta

about:
  summary: "A meta-package for creating installers."
