about:
  summary: "A meta-package for building all the dependencies needed for the minimal, headless version of pixel/object classification."

package:
  name: ilastik-deps-pc-headless
  version: "1.2"

build:
  number: 1

requirements:
  run:
    - python
    - numpy
    - vigra
    - fastfilters # [unix]
    - tifffile
    - h5py
    - psutil
    - greenlet
    - yapsy
    - scikit-learn
    - scikit-image
    - faulthandler # [py2k]
    - jsonschema
    - ilastik-feature-selection >=0.123.post9
    - nose
    #- blist # only needed by deprecated operators
    